export interface GameMeta {
  id: string
  title: string
  author: string
  /** цвет-заливка иконки автора (как круглая иконка под карточкой) */
  authorColor: string
  category:
    | 'obby' | 'sandbox' | 'rp' | 'race' | 'sim'
    | 'tower' | 'garden' | 'pets' | 'town'
    | 'fashion' | 'mystery' | 'nights'
    | 'tycoon' | 'ability' | 'petbrain'
  emoji: string
  color: string
  playersOnline: number
  views: number
  likes: number
  featured: boolean
  template: boolean
  hot: boolean
  fresh: boolean
  rank: number
  scene: 'playground'
}

export const GAMES: GameMeta[] = [
  // ─── Roblox-clone capstone worlds (educational remakes) ───
  {
    id: 'tower-of-code',
    title: 'Башня Кода',
    author: 'Эдюсон KidsStudio',
    authorColor: '#6B5CE7',
    category: 'tower',
    emoji: '🗼',
    color: '#6B5CE7',
    playersOnline: 14,
    views: 8420,
    likes: 302,
    featured: true,
    template: true,
    hot: true,
    fresh: true,
    rank: 1,
    scene: 'playground',
  },
  {
    id: 'growbot-garden',
    title: 'Огород Бота',
    author: 'Эдюсон KidsStudio',
    authorColor: '#34C38A',
    category: 'garden',
    emoji: '🌱',
    color: '#9FE8C7',
    playersOnline: 9,
    views: 5210,
    likes: 178,
    featured: true,
    template: true,
    hot: false,
    fresh: true,
    rank: 2,
    scene: 'playground',
  },
  {
    id: 'pet-math-sim',
    title: 'Питомцы-математики',
    author: 'Эдюсон KidsStudio',
    authorColor: '#c879ff',
    category: 'pets',
    emoji: '🐾',
    color: '#c879ff',
    playersOnline: 11,
    views: 6740,
    likes: 221,
    featured: true,
    template: true,
    hot: true,
    fresh: true,
    rank: 3,
    scene: 'playground',
  },
  {
    id: 'bot-town',
    title: 'Городок Ботов',
    author: 'Эдюсон KidsStudio',
    authorColor: '#5AA9FF',
    category: 'town',
    emoji: '🏙',
    color: '#A9D8FF',
    playersOnline: 6,
    views: 3890,
    likes: 124,
    featured: true,
    template: true,
    hot: false,
    fresh: true,
    rank: 4,
    scene: 'playground',
  },
  {
    id: 'fashion-runway',
    title: 'Модный Показ',
    author: 'Эдюсон KidsStudio',
    authorColor: '#FFB4C8',
    category: 'fashion',
    emoji: '👗',
    color: '#ff5ab1',
    playersOnline: 12,
    views: 4890,
    likes: 198,
    featured: true,
    template: true,
    hot: true,
    fresh: true,
    rank: 5,
    scene: 'playground',
  },
  {
    id: 'detective-mansion',
    title: 'Детектив в Особняке',
    author: 'Эдюсон KidsStudio',
    authorColor: '#6B5CE7',
    category: 'mystery',
    emoji: '🔍',
    color: '#3d3148',
    playersOnline: 7,
    views: 2760,
    likes: 94,
    featured: true,
    template: true,
    hot: false,
    fresh: true,
    rank: 6,
    scene: 'playground',
  },
  {
    id: 'forest-nights',
    title: '99 Ночей в Лесу',
    author: 'Эдюсон KidsStudio',
    authorColor: '#FFD43C',
    category: 'nights',
    emoji: '🏕',
    color: '#0c0a2a',
    playersOnline: 9,
    views: 4120,
    likes: 167,
    featured: true,
    template: true,
    hot: true,
    fresh: true,
    rank: 7,
    scene: 'playground',
  },
  {
    id: 'brainrot-tycoon',
    title: 'Империя Плинтов',
    author: 'Эдюсон KidsStudio',
    authorColor: '#FFD43C',
    category: 'tycoon',
    emoji: '🏛',
    color: '#FFD43C',
    playersOnline: 15,
    views: 9340,
    likes: 412,
    featured: true,
    template: true,
    hot: true,
    fresh: true,
    rank: 8,
    scene: 'playground',
  },
  {
    id: 'ability-builder',
    title: 'Огненный Шар',
    author: 'Эдюсон KidsStudio',
    authorColor: '#ff5464',
    category: 'ability',
    emoji: '🔥',
    color: '#ff5464',
    playersOnline: 18,
    views: 11200,
    likes: 487,
    featured: true,
    template: true,
    hot: true,
    fresh: true,
    rank: 9,
    scene: 'playground',
  },
  {
    id: 'pet-brain',
    title: 'Мой Питомец',
    author: 'Эдюсон KidsStudio',
    authorColor: '#FFB4C8',
    category: 'petbrain',
    emoji: '🐶',
    color: '#FFB4C8',
    playersOnline: 13,
    views: 7820,
    likes: 341,
    featured: true,
    template: true,
    hot: true,
    fresh: true,
    rank: 10,
    scene: 'playground',
  },
  // ─── Classic worlds ───
  {
    id: 'obby-rainbow',
    title: 'Прыжки по цветам',
    author: 'EdusonStudio',
    authorColor: '#ff5464',
    category: 'obby',
    emoji: '🟥',
    color: '#ff5ab1',
    playersOnline: 8,
    views: 10700,
    likes: 217,
    featured: true,
    template: false,
    hot: true,
    fresh: false,
    rank: 5,
    scene: 'playground',
  },
  {
    id: 'farm-garden',
    title: 'Вырасти сад 0.2 (КИТАЙ)',
    author: 'GGlazStudio',
    authorColor: '#ff5464',
    category: 'sim',
    emoji: '🌱',
    color: '#5ba55b',
    playersOnline: 2,
    views: 10700,
    likes: 217,
    featured: true,
    template: true,
    hot: true,
    fresh: false,
    rank: 2,
    scene: 'playground',
  },
  {
    id: 'farm-2',
    title: 'Grow a Farm',
    author: 'vian',
    authorColor: '#4c97ff',
    category: 'sim',
    emoji: '🌾',
    color: '#ffd644',
    playersOnline: 1,
    views: 5300,
    likes: 116,
    featured: true,
    template: false,
    hot: false,
    fresh: true,
    rank: 3,
    scene: 'playground',
  },
  {
    id: 'bendy',
    title: 'Тёмная чернильница · Глава 1',
    author: 'Студия Тень',
    authorColor: '#2a2840',
    category: 'rp',
    emoji: '🎩',
    color: '#2a2840',
    playersOnline: 0,
    views: 7200,
    likes: 175,
    featured: true,
    template: false,
    hot: false,
    fresh: false,
    rank: 4,
    scene: 'playground',
  },
  {
    id: 'tsunami',
    title: '[МИНИ-UPD] Спаси брейнрота от ЦУНами',
    author: 'Tsidos [T1SbO]',
    authorColor: '#c879ff',
    category: 'sandbox',
    emoji: '🌊',
    color: '#4c97ff',
    playersOnline: 0,
    views: 14100,
    likes: 196,
    featured: true,
    template: false,
    hot: false,
    fresh: false,
    rank: 5,
    scene: 'playground',
  },
  {
    id: 'burger-sim',
    title: 'Бургер Симулятор',
    author: 'HerryLayes',
    authorColor: '#ff5ab1',
    category: 'sim',
    emoji: '🍔',
    color: '#ffd644',
    playersOnline: 0,
    views: 11300,
    likes: 265,
    featured: true,
    template: false,
    hot: true,
    fresh: false,
    rank: 6,
    scene: 'playground',
  },
  {
    id: 'crafter',
    title: 'крафтер (1 13)',
    author: 'Ananas',
    authorColor: '#ffd644',
    category: 'sandbox',
    emoji: '⛏️',
    color: '#ffd1e8',
    playersOnline: 1,
    views: 6300,
    likes: 150,
    featured: true,
    template: false,
    hot: false,
    fresh: false,
    rank: 7,
    scene: 'playground',
  },
  {
    id: 'city-rp',
    title: 'Город RP - 404.. ЛЕСНИЧЕСТВО',
    author: 'караМЕЛь',
    authorColor: '#5ba55b',
    category: 'rp',
    emoji: '🏙️',
    color: '#4c97ff',
    playersOnline: 0,
    views: 4700,
    likes: 76,
    featured: true,
    template: false,
    hot: false,
    fresh: false,
    rank: 8,
    scene: 'playground',
  },
  {
    id: 'mystery-long',
    title: 'Тайна Длинного существа',
    author: 'караМЕЛь',
    authorColor: '#5ba55b',
    category: 'rp',
    emoji: '👁️',
    color: '#2a2840',
    playersOnline: 1,
    views: 3200,
    likes: 91,
    featured: false,
    template: false,
    hot: false,
    fresh: false,
    rank: 9,
    scene: 'playground',
  },
  {
    id: 'obby-likes',
    title: 'obby ставьте лайки, скоро обнова',
    author: 'МГ',
    authorColor: '#a4a9bc',
    category: 'obby',
    emoji: '🎈',
    color: '#88d4ff',
    playersOnline: 0,
    views: 11300,
    likes: 244,
    featured: false,
    template: false,
    hot: false,
    fresh: false,
    rank: 10,
    scene: 'playground',
  },
  {
    id: 'race-ice',
    title: 'ЛЁД 1\\2 (1961год)',
    author: 'hdhjjsjjf2',
    authorColor: '#2a3340',
    category: 'race',
    emoji: '🧊',
    color: '#2a3340',
    playersOnline: 0,
    views: 4700,
    likes: 72,
    featured: false,
    template: false,
    hot: false,
    fresh: true,
    rank: 11,
    scene: 'playground',
  },
  {
    id: 'forest-99',
    title: '99 ночей в лесу (как)',
    author: 'МАФИОЗО',
    authorColor: '#ffd644',
    category: 'sandbox',
    emoji: '🌲',
    color: '#1f5f2f',
    playersOnline: 2,
    views: 2800,
    likes: 48,
    featured: false,
    template: false,
    hot: false,
    fresh: true,
    rank: 12,
    scene: 'playground',
  },
  {
    id: 'worst-space',
    title: 'худший спейс!!!',
    author: 'паркурист 999',
    authorColor: '#4c97ff',
    category: 'sandbox',
    emoji: '🟦',
    color: '#88d4ff',
    playersOnline: 1,
    views: 1200,
    likes: 14,
    featured: false,
    template: false,
    hot: false,
    fresh: true,
    rank: 13,
    scene: 'playground',
  },
  {
    id: 'tree-chop',
    title: 'Наруби Дерева',
    author: 'Дядя Женя',
    authorColor: '#8b4513',
    category: 'sim',
    emoji: '🪓',
    color: '#5ba55b',
    playersOnline: 22,
    views: 9800,
    likes: 304,
    featured: false,
    template: false,
    hot: true,
    fresh: false,
    rank: 14,
    scene: 'playground',
  },
  {
    id: 'cat-city',
    title: 'Город кошек',
    author: 'Евик',
    authorColor: '#ff8c1a',
    category: 'rp',
    emoji: '🐱',
    color: '#ffd1e8',
    playersOnline: 0,
    views: 7500,
    likes: 140,
    featured: false,
    template: false,
    hot: false,
    fresh: false,
    rank: 15,
    scene: 'playground',
  },
  {
    id: 'steal-brain',
    title: 'Украдите мозгавую чтобы ...',
    author: 'ШКОЛА 1566',
    authorColor: '#ff5464',
    category: 'rp',
    emoji: '🧠',
    color: '#88d4ff',
    playersOnline: 0,
    views: 3400,
    likes: 78,
    featured: false,
    template: false,
    hot: false,
    fresh: true,
    rank: 16,
    scene: 'playground',
  },
]

export function findGame(id: string): GameMeta | undefined {
  return GAMES.find((g) => g.id === id)
}
