// Auto-generated barrel: re-exports all world prop components
// Split from WorldAdditions.tsx (29,895 LOC → 30 modules)

export * from './primitives'
export * from './mechanics'
export * from './architecture'
export * from './food'
export * from './scifi'
export * from './fantasy'
export * from './kitchenCamping'
export * from './halloweenToysLab'
export * from './farmPiratesJungle'
export * from './cityGardenSport'
export * from './nordicMagicalIndustrial'
export * from './dinoWesternIce'
export * from './magicEffectsSuperhero'
export * from './transport2FoodSports2'
export * from './batch8FantasyScitech'
export * from './batch9to10'
export * from './batch11to12'
export * from './batch13to14'
export * from './batch15to16'
export * from './batch17to18'
export * from './batch19to20'
export * from './batch21to22'
export * from './batch23to24'
export * from './batch25to26'
export * from './batch27to28'
export * from './batch29to30'
export * from './batch31to32'
export * from './batch33to34'
export * from './batch35to36'
export * from './batch37to41'
